name: Reusable Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, labeled ]
jobs:
  test-action:
  
    uses: aravindkumarmg/docker-images/.github/workflows/nodejs.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
